### ISSUE TITLE
As a visitor, I can give feedback through the main page by...

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#255]
selecting 3 smileys titled- “How did we do today?”

- [x] Create a new table in database to collect feedback #256 - *1.5 days*
- [x] Create front end view with buttons that update the database - *1 day*
- [x] Create front end view for cb-admin to see their feedback #280 - *2 days*
- [ ] ~~Create front end view for twine-admins to see all cbs feedback #304 - *2 days*~~
