### ISSUE TITLE
Implementing Re-design

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/DataPower#302]
Pages/views:

### CB Admin
* [x] dashboard (#310)
* [x] profile (#319)
* [x] visitor dashboard (#332)
* [x] visitor details (#323)
* [x] visitor feedback (#281)
* [x] visitor profile (#322)
* [x] activities (#330)
* [x] password confirmation (#299)
* [x] signup (#299)
* [x] login (#299)
* [x] forgot password (#299)
* [x] reset password (#299)

### Other
* [x] Who are you? (#299)

### Visitor
* [x] home page (#313)
* [x] signup (#303)
* [x] QR code page (#303)
* [x] login (QR scan) (#320)
* [x] activities (#320)
* [x] feedback thanks (#328)
