### ISSUE TITLE
Workshop preparation

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/DataPower#388]
### Tasks
* [ ] Study existing data flows 
* [ ] Compare with "idealised" data flows
* [ ] Determine existing data model in other apps
* [ ] Infer technical infrastructure requirements from business requirements

**Comment by eliascodes** [comment]
API used by the mobile app:
```
DELETE /logs/:id
GET    /logs/:id
PUT    /logs/:id
POST   /logs
POST   /logs/sync
GET    /logs/user/:id
GET    /logs/admin/:id
GET    /logs/user/:id/total
GET    /logs/user/:id/total/days/:days
GET    /logs/user/:id/total/date/:date

DELETE /meetings
GET    /meetings/user/:id
GET    /meetings/:id
PUT    /meetings/:id
POST   /meetings
POST   /meetings/sync

GET    /users/:id
PUT    /users/:id
GET    /users/login
POST   /users

GET    /volunteers/organisation/:id
GET    /volunteers/:id
PUT    /volunteers/:id
POST   /volunteers

GET    /genders

GET    /meetingTypes

GET    /outreaches/:id
GET    /outreaches/:org_id/bytype/:type
DELETE /outreaches/:id
PUT    /outreaches/:id
POST   /outreaches
GET    /outreacheTypes
GET    /outreachChildTypes/parent/:id

GET    /activities

GET    /regions
GET    /regions/:id/organisations

GET    /organisations/:id/summary
```
